name: Generate Changelog

on:
  push:
    tags:
      - '*.*.*' # Se ejecuta solo para tags estilo x.y.z

permissions:
  contents: write # Necesario para hacer commit autom√°tico

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para obtener el historial completo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install changelog generator
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit changelog
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for $GITHUB_REF_NAME" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
